export {default as CategoriesFormPage} from "./admin/Categories/CategoriesFormPage"
export {default as CategoriesListPage} from "./admin/Categories/CategoriesListPage"
export {default as ProductFormPage} from "./admin/product/ProductFormPage"
export {default as ProductListPage} from "./admin/product/ProductListPage"
export {default as HomePage} from "./user/HomePage"
export {default as LoginPage} from "./user/LoginPage"
export {default as SignUpPage} from "./user/SignUpPage"
export {default as NotFound} from "./user/NotFound"