spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 80MB
      max-request-size: 60MB

file:
  upload-dir: products

